app/urls.py
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView

from .views import PropertiesListViewList, PropertiesListViewGrid, EstateView

urlpatterns = [
    path('properties_list/<int:page>/', PropertiesListViewList.as_view(), name='properties-list-page'),
    path('properties_grid/<int:page>/', PropertiesListViewGrid.as_view(), name='properties-grid-page'),
    path('properties_list/', RedirectView.as_view(url=reverse_lazy('properties-list-page', kwargs={'page': 1})), name='properties-list'),
    path('properties_grid/', RedirectView.as_view(url=reverse_lazy('properties-grid-page', kwargs={'page': 1})), name='properties-grid'),
    path('estate/<int:pk>/', EstateView.as_view(), name='estate'),
    path('', RedirectView.as_view(url=reverse_lazy('properties-list-page', kwargs={'page': 1})), name='app')
]

square/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('auth/', include('app_auth.urls')),
    path('app/', include('app.urls')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url=reverse_lazy('app'))),
]

models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Address(models.Model):
    country = models.CharField(max_length=60, blank=True, null=True)
    area = models.CharField(max_length=60, blank=True, null=True)
    city = models.CharField(max_length=60, blank=True, null=True)
    region = models.CharField(max_length=60, blank=True, null=True)
    street = models.CharField(max_length=60, blank=True, null=True)
    housenumber = models.CharField(max_length=60, blank=True, null=True)
    metro = models.CharField(max_length=60, blank=True, null=True)
    realestateid = models.ForeignKey('Realestate', models.DO_NOTHING, db_column='realestateid', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'address'


class DirectLink(models.Model):
    link = models.CharField(unique=True, max_length=250)
    realestateid = models.ForeignKey('Realestate', models.DO_NOTHING, db_column='realestateid', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'directlink'


class Photo(models.Model):
    url = models.CharField(max_length=250)
    realestateid = models.ForeignKey('Realestate', models.DO_NOTHING, db_column='realestateid', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'photo'


class Price(models.Model):
    price = models.TextField()  # This field type is a guess.
    area = models.IntegerField()
    realestateid = models.ForeignKey('Realestate', models.DO_NOTHING, db_column='realestateid', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'price'


class RealEstate(models.Model):
    title = models.CharField(max_length=150)
    type = models.CharField(max_length=150)
    description = models.TextField()
    pricepersquaremeter = models.TextField()  # This field type is a guess.

    class Meta:
        managed = False
        db_table = 'realestate'


class RealEstateResource(models.Model):
    realestateid = models.ForeignKey(Realestate, models.DO_NOTHING, db_column='realestateid', blank=True, null=True)
    resourceid = models.ForeignKey('Resource', models.DO_NOTHING, db_column='resourceid', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'realestate_resource'


class Resource(models.Model):
    title = models.CharField(max_length=30, blank=True, null=True)
    link = models.CharField(unique=True, max_length=250)

    class Meta:
        managed = False
        db_table = 'resource'

app_data/templates/app/app_base.html
{% extends 'base.html' %}
{% load static %}

{% block add_style %}
    <link rel="stylesheet" href="{% static 'app/bundles/app.bundle.css' %}">
{% endblock %}

{% block add_scripts %}
    <script src="{% static 'app/bundles/app.bundle.js' %}"></script>
{% endblock %}

{% block content %}
    {% include 'app/components/header.html' %}
    {% include 'app/components/filters.html' %}

    {% block app_content %}
    {% endblock %}
{% endblock %}

app_data/templates/app/app_full_page_base.html
{% extends 'base.html' %}
{% load static %}

{% block add_style %}
    <link rel="stylesheet" href="{% static 'app/bundles/app.bundle.css' %}">
{% endblock %}

{% block add_scripts %}
    <script src="{% static 'app/bundles/app.bundle.js' %}"></script>
{% endblock %}

{% block content %}
    {% include 'components/header_back.html' %}

    {% block app_content %}
    {% endblock %}
{% endblock %}

app_data/templates/app/estate.html
{% extends 'app/app_full_page_base.html' %}
{% load static %}
{% load ext_filters %}

{% block app_content %}
    <div class="app-content">
        <div class="app-container-list">

            <section>
                <div class="ratio-16-9 mb-4">
                    <div class="ratio-inner">
                        <div class="slider-container touches">
                            <div class="slider-elements">
                                {% with photo_count=re.photo_set.count %}
                                {% for photo in re.photo_set.all %}
                                    <div><img src="{{ photo.url }}" data-fancybox="gallery"></div>
                                {% empty %}
                                    <div>
                                        <a href="#" class="estate-list-more-photo">
                                            <span>Нет фото</span>
                                        </a>
                                    </div>
                                {% endfor %}
                                {% endwith %}
                            </div>
                            <div class="slider-counter"></div>
                            <div class="slider-arrow-left">
                                <div>
                                    <img width="100%" height="auto" src="{% static 'square/icons/arrow_backward.svg' %}">
                                </div>
                            </div>
                            <div class="slider-arrow-right">
                                <div>
                                    <img width="100%" height="auto" src="{% static 'square/icons/arrow_forward.svg' %}">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section>
                <div class="estate-component-data-surface">
                    <div class="d-flex flex-md-row flex-column">
                        <div class="flex-grow-1 mb-md-0 mb-4">
                            <div class="estate-component-title">{{ re.title }}</div>
                            {% with price_elem=re.price_set.first %}
                                {% if price_elem is not None %}
                                    <div class="estate-component-price">{{ price_elem.price }}</div>
                                {% endif %}
                            {% endwith %}
                            {% with pricepersquaremeter=re.pricepersquaremeter %}
                                {% if pricepersquaremeter %}
                                    <div class="estate-component-price-per-square mb-4">{{ pricepersquaremeter }}/м²</div>
                                {% endif %}
                            {% endwith %}

                            {% with address_elem=re.address_set.first %}
                                <div class="estate-component-address mb-2">{{ address_elem|ext_getstrvalues|slice:"1:7"|ext_removeempty|join:", " }}</div>
                                {% if address_elem.metro %}
                                    <div class="estate-component-address d-flex align-items-center">
                                        <img class="icon-std" src="{% static 'square/icons/metro.svg' %}">
                                        <span class="ms-2">{{ address_elem.metro }}</span>
                                    </div>
                                {% endif %}
                            {% endwith %}
                        </div>
                        <div class="d-flex flex-md-column flex-row align-items-stretch">
                            <button class="button-outlined mb-md-4 mb-0">
                                <span>В избранное</span>
                                <svg class="icon-std ms-1" viewBox="0 0 18 18">
                                    <use class="class-use" href="{% static 'square/icons/like.svg' %}#likeSVG"></use>
                                </svg>
                            </button>
                            <button class="estate-component-resource-button button-primary-tool mt-md-auto mt-0 ms-md-0 ms-auto">
                                <span>Перейти</span>
                                <svg class="icon-std ms-1" viewBox="0 0 16 9">
                                    <use class="class-use" href="{% static 'square/icons/expand_non_filled.svg' %}#expandSVG"></use>
                                </svg>
                                <div class="estate-component-resource-list">
                                    {% with direct_link=re.directlink.link %}
                                    {% if direct_link is not None %}
                                        <!--<a href="#" target="_blank">
                                            <img style="width:auto; height: 3rem" src="{% static 'square/images/cian_logo.png' %}">
                                        </a>-->
                                        {% if resource_provider == 'dom_rf' %}
                                            <a href="{{ direct_link }}" target="_blank">
                                                <img style="width:auto; height: 3rem" src="{% static 'square/images/dom-rf_logo.svg' %}">
                                            </a>
                                        {% endif %}
                                        <!--<a href="#" target="_blank">
                                            <img style="width:100%; height: auto" src="{% static 'square/images/invest-moscow_logo.svg' %}">
                                        </a>-->
                                        {% if resource_provider == 'kf' %}
                                            <a href="{{ direct_link }}" target="_blank">
                                                <img style="width:auto; height: 3rem" src="{% static 'square/images/knight_frank_logo.png' %}">
                                            </a>
                                        {% endif %}
                                        <!--<a href="#" target="_blank">
                                            <img style="width:auto; height: 3rem" src="{% static 'square/images/osobnyaki_logo.svg' %}">
                                        </a>-->
                                        <!--<a href="#" target="_blank">
                                            <img style="width:100%; height: auto" src="{% static 'square/images/rad_logo.svg' %}">
                                        </a>-->
                                        <!--<a href="#" target="_blank">
                                            <img style="width:auto; height: 3rem" src="{% static 'square/images/river_logo.svg' %}">
                                        </a>-->
                                        <!--<a href="#" target="_blank">
                                            <img style="width:100%; height: auto" src="{% static 'square/images/trast_logo.svg' %}">
                                        </a>-->
                                    {% endif %}
                                    {% endwith %}
                                    {% if resource_provider is None %}
                                        <span>
                                            Нет прямой ссылки
                                        </span>
                                    {% endif %}
                                </div>
                            </button>
                        </div>
                    </div>
                </div>
            </section>

            <section>
                <ul class="estate-component-params">
                    {% if re.type %}
                        <li>
                            <div>{{ re.type }}</div>
                            <span>Тип объекта</span>
                        </li>
                    {% endif %}
                    <!--<li>
                        <div>Аренда</div>
                        <span>Тип сделки</span>
                    </li>-->
                </ul>
            </section>

            {% if re.description %}
                <section>
                    <div class="estate-component-section-title">Описание</div>
                    <div class="estate-component-description">
                        {{ re.description }}
                    </div>
                </section>
            {% endif %}

            {% if re.price_set.count > 0 %}
                <section>
                    <div class="estate-component-section-title">Варианты помещений</div>
                    <div class="estate-component-table">
                        <table>
                            <tbody>
                                <tr>
                                    <th>Стоимость (руб.)</th>
                                    <th>м²</th>
                                    <th>руб/м²</th>
                                </tr>
                                {% for price_elem in re.price_set.all %}
                                    <tr>
                                        <td>{{ price_elem.price }}</td>
                                        <td>{{ price_elem.area }} м²</td>
                                        {% if re.pricepersquaremeter %}
                                            <td>{{ re.pricepersquaremeter }}/м²</td>
                                        {% else %}
                                            <td></td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </section>
            {% endif %}

            <section>
                <div class="estate-component-section-title">Расположение</div>
                {% with address_elem=re.address_set.first %}
                    <div class="estate-component-address mb-2">{{ address_elem|ext_getstrvalues|slice:"1:7"|ext_removeempty|join:", " }}</div>
                    {% if address_elem.metro %}
                        <div class="estate-component-address d-flex align-items-center">
                            <img class="icon-std" src="{% static 'square/icons/metro.svg' %}">
                            <span class="ms-2">{{ address_elem.metro }}</span>
                        </div>
                    {% endif %}
                {% endwith %}
            </section>
        </div>
    </div>
{% endblock %}

app_data/templates/app/properties_grid.html
{% extends 'app/app_base.html' %}
{% load static %}
{% load ext_filters %}

{% block app_content %}
    <div class="app-content">
        <div class="app-container-toolbar">
            {% include 'app/components/toolbar.html' %}
        </div>
        {% include 'app/components/pagination.html' %}
        <div class="app-container-grid">

            <div class="estate-grid">
                <div class="row">
                    <!-- single element -->
                    {% for re in realestates %}
                        {% with price_elem=re.price_set.first %}
                        {% with address_elem=re.address_set.first %}
                        {% with description=re.description %}
                        <div class="col-xl-4 col-lg-6 col-12 mb-5">
                            <div class="ratio-16-9">
                                <div class="ratio-inner">
                                    <a href="{% url 'estate' pk=re.pk %}" class="d-block w-100 h-100">
                                        <div class="slider-container">
                                            <div class="slider-elements">
                                                {% with photo=re.photo_set.first %}
                                                    {% if photo %}
                                                        <div><img src="{{ photo.url }}"></div>
                                                    {% endif %}
                                                {% endwith %}
                                            </div>
                                            <div class="slider-overflow-content stable">
                                                <div class="flex-grow-1"></div>
                                                <div class="estate-grid-title">{{ re.title }}</div>
                                                <div class="estate-grid-address">{{ address_elem|ext_getstrvalues|slice:"1:7"|ext_removeempty|join:", " }}</div>

                                                {% if price_elem is not None %}
                                                    <div class="estate-grid-data">
                                                        <span class="me-auto">
                                                            {{ price_elem.area }} м²
                                                        </span>
                                                        <span>
                                                            {{ price_elem.price }}
                                                        </span>
                                                    </div>
                                                {% endif %}
                                            </div>
                                            <div class="slider-overflow-content-hover">
                                                <div class="estate-grid-title small">{{ re.title }}</div>
                                                <div class="estate-grid-address">{{ address_elem|ext_getstrvalues|slice:"1:7"|ext_removeempty|join:", " }}</div>
                                                {% if address_elem.metro %}
                                                    <div class="estate-grid-address d-flex align-items-center">
                                                        <img class="icon-std" src="{% static 'square/icons/metro.svg' %}">
                                                        <span class="ms-2">{{ address_elem.metro }}</span>
                                                    </div>
                                                {% endif %}
                                                {% if description %}
                                                    <div class="estate-grid-description">{{ description }}</div>
                                                {% endif %}
                                                <div class="flex-grow-1"></div>
                                                {% if price_elem is not None %}
                                                    <div class="estate-grid-data">
                                                        <span class="me-auto">
                                                            {{ price_elem.area }} м²
                                                        </span>
                                                        <span>
                                                            {{ price_elem.price }}
                                                        </span>
                                                    </div>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                        {% endwith %}
                        {% endwith %}
                        {% endwith %}
                    {% endfor %}
                    <!-- end of single element  -->
                </div>
            </div>
        </div>

        {% include 'app/components/pagination.html' %}
    </div>
{% endblock %}

app_data/templates/app/properties_list.html
{% extends 'app/app_base.html' %}
{% load static %}
{% load ext_filters %}

{% block app_content %}
    <div class="app-content">
        <div class="app-container-toolbar">
            {% include 'app/components/toolbar.html' %}
        </div>
        {% include 'app/components/pagination.html' %}
        <div class="app-container-list">

            <!-- single element -->
            {% for re in realestates %}
                <div class="estate-list">
                    <div class="row">
                        <div class="col-md-4 col-12 mb-4">
                            <div class="ratio-16-9">
                                <div class="ratio-inner">
                                    <div class="slider-container">
                                        <div class="slider-elements">
                                            {% with photo_count=re.photo_set.count %}
                                            {% for photo in re.photo_set.all|slice:":5" %}
                                                <div><img src="{{ photo.url }}" data-fancybox="gallery_{{ forloop.parentloop.counter }}"></div>
                                                {% if forloop.last %}
                                                    <div>
                                                        <img src="{{ photo.url }}" data-fancybox="gallery_{{ forloop.parentloop.counter }}">
                                                        <a href="{% url 'estate' pk=re.pk %}" class="estate-list-more-photo">
                                                            <span>Смотреть все фото ({{ photo_count }})</span>
                                                        </a>
                                                    </div>
                                                {% endif %}
                                            {% empty %}
                                                <div>
                                                    <a href="#" class="estate-list-more-photo">
                                                        <span>Нет фото</span>
                                                    </a>
                                                </div>
                                            {% endfor %}
                                            {% endwith %}
                                        </div>
                                        <div class="slider-dots-container"></div>
                                        <div class="slider-arrow-left">
                                            <div>
                                                <img width="100%" height="auto" src="{% static 'square/icons/arrow_backward.svg' %}">
                                            </div>
                                        </div>
                                        <div class="slider-arrow-right">
                                            <div>
                                                <img width="100%" height="auto" src="{% static 'square/icons/arrow_forward.svg' %}">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-5 col-12 estate-list-body mb-4">
                            <a href="{% url 'estate' pk=re.pk %}" class="estate-list-title mb-1">{{ re.title }}</a>
                            {% with address_elem=re.address_set.first %}
                                <div class="estate-list-address mb-3">
                                    {{ address_elem|ext_getstrvalues|slice:"1:7"|ext_removeempty|join:", " }}
                                </div>
                                {% if address_elem.metro %}
                                    <div class="estate-list-address d-flex align-items-center mb-3">
                                        <img class="icon-std" src="{% static 'square/icons/metro.svg' %}">
                                        <span class="ms-2">{{ address_elem.metro }}</span>
                                    </div>
                                {% endif %}
                            {% endwith %}
                            {% with description=re.description %}
                                {% if description %}
                                    <div class="estate-list-description-wrapper">
                                        <div class="estate-list-description mb-4">{{ description }}</div>
                                    </div>
                                {% endif %}
                            {% endwith %}
                            {% with price_elem=re.price_set.first %}
                                {% if price_elem is not None %}
                                    <div class="estate-list-square">{{ price_elem.area }} м²</div>
                                {% endif %}
                            {% endwith %}
                        </div>
                        <div class="col-md-3 col-12 d-flex">
                            <div class="ms-md-auto ms-md-0 ms-auto">
                                {% with price_elem=re.price_set.first %}
                                    {% if price_elem is not None %}
                                        <div class="estate-list-price text-end mb-1">{{ price_elem.price }}</div>
                                    {% endif %}
                                {% endwith %}
                                {% with pricepersquaremeter=re.pricepersquaremeter %}
                                    {% if pricepersquaremeter %}
                                        <div class="estate-list-price-per-square text-end mb-2">{{ pricepersquaremeter }}/м²</div>
                                    {% endif %}
                                {% endwith %}
                                <div class="text-end">
                                    <button class="button-outlined-small">
                                        <span>В избранное</span>
                                        <svg class="icon-std ms-1" viewBox="0 0 18 18">
                                            <use class="class-use" href="{% static 'square/icons/like.svg' %}#likeSVG"></use>
                                        </svg>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <!-- end of single element  -->
        </div>

        {% include 'app/components/pagination.html' %}
    </div>
{% endblock %}